#
# GitHub Actions workflow for Drupal code quality and security
# Copy to .github/workflows/quality.yml
#
# Prerequisites:
#   - DDEV configured in project
#   - Quality tools installed via composer (PHPStan, PHPMD, PHPCPD, Coder)
#   - Security tools installed via composer (Psalm, php-security-linter)
#   - CODECOV_TOKEN secret (optional, for coverage upload)
#

name: Code Quality

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  COVERAGE_MINIMUM: 70
  COVERAGE_TARGET: 80
  DUPLICATION_MAX: 5

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup DDEV
        uses: ddev/github-action-setup-ddev@v1
        with:
          autostart: true

      - name: Install dependencies
        run: ddev composer install --no-interaction

      - name: Install quality tools
        run: |
          ddev composer require --dev \
            phpstan/phpstan \
            mglaman/phpstan-drupal \
            phpstan/extension-installer \
            phpmd/phpmd \
            systemsdk/phpcpd \
            drupal/coder \
            vimeo/psalm \
            yousha/php-security-linter \
            --no-interaction

      # =====================
      # Static Analysis
      # =====================
      - name: PHPStan Analysis
        run: |
          ddev exec vendor/bin/phpstan analyse \
            web/modules/custom \
            --level=8 \
            --error-format=github \
            --no-progress
        continue-on-error: true

      # =====================
      # Code Smells
      # =====================
      - name: PHPMD Analysis
        run: |
          ddev exec vendor/bin/phpmd \
            web/modules/custom \
            github \
            cleancode,codesize,design
        continue-on-error: true

      # =====================
      # Duplication Check
      # =====================
      - name: PHPCPD Duplication
        run: |
          ddev exec vendor/bin/phpcpd \
            --min-lines=10 \
            --min-tokens=70 \
            --exclude=tests \
            web/modules/custom
        continue-on-error: true

      # =====================
      # Coding Standards
      # =====================
      - name: Drupal Coding Standards
        run: |
          ddev exec vendor/bin/phpcs \
            --standard=Drupal,DrupalPractice \
            --extensions=php,module,inc,install \
            --report=checkstyle \
            web/modules/custom
        continue-on-error: true

      # =====================
      # Security Audit
      # =====================
      - name: Psalm Taint Analysis
        run: |
          ddev exec vendor/bin/psalm \
            --taint-analysis \
            --no-cache \
            --output-format=github \
            web/modules/custom web/themes/custom
        continue-on-error: true

      - name: PHP Security Linter (OWASP/CIS)
        run: |
          ddev exec vendor/bin/php-security-linter scan \
            web/modules/custom web/themes/custom \
            --format=github
        continue-on-error: true

      - name: Drush Security Advisories
        run: |
          ddev drush pm:security --format=list
        continue-on-error: true

      - name: Composer Audit
        run: |
          ddev composer audit --no-dev
        continue-on-error: false

      - name: Semgrep SAST
        run: |
          ddev exec semgrep scan --config=auto --sarif \
            web/modules/custom web/themes/custom
        continue-on-error: true

      - name: Trivy Scanner
        run: |
          trivy fs --scanners vuln,secret --format sarif --output trivy-results.sarif .
        continue-on-error: true

      - name: Gitleaks Secret Detection
        run: |
          gitleaks detect --no-git --report-format sarif --report-path gitleaks-results.sarif
        continue-on-error: true

      # =====================
      # Tests with Coverage
      # =====================
      - name: Run Tests with Coverage
        run: |
          ddev exec php -d pcov.enabled=1 \
            vendor/bin/phpunit \
            --testsuite unit,kernel \
            --coverage-clover coverage.xml \
            --coverage-text

      - name: Check Coverage Threshold
        run: |
          COVERAGE=$(grep -oP 'line-rate="\K[\d.]+' coverage.xml | head -1 || echo "0")
          COVERAGE_PCT=$(echo "$COVERAGE * 100" | bc)
          echo "Coverage: ${COVERAGE_PCT}%"

          if (( $(echo "$COVERAGE_PCT < $COVERAGE_MINIMUM" | bc -l) )); then
            echo "::error::Coverage ${COVERAGE_PCT}% is below minimum ${COVERAGE_MINIMUM}%"
            exit 1
          elif (( $(echo "$COVERAGE_PCT < $COVERAGE_TARGET" | bc -l) )); then
            echo "::warning::Coverage ${COVERAGE_PCT}% is below target ${COVERAGE_TARGET}%"
          else
            echo "::notice::Coverage ${COVERAGE_PCT}% meets target"
          fi

      # =====================
      # Upload Coverage
      # =====================
      - name: Upload to Codecov
        if: github.event_name == 'push'
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}

      # =====================
      # Summary Report
      # =====================
      - name: Generate Summary
        if: always()
        run: |
          echo "## Code Quality Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Quality Checks" >> $GITHUB_STEP_SUMMARY
          echo "| Check | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| PHPStan | ${{ steps.phpstan.outcome || 'completed' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| PHPMD | ${{ steps.phpmd.outcome || 'completed' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Duplication | ${{ steps.phpcpd.outcome || 'completed' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Coding Standards | ${{ steps.phpcs.outcome || 'completed' }} |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Security Checks" >> $GITHUB_STEP_SUMMARY
          echo "| Check | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Psalm Taint Analysis | ${{ steps.psalm.outcome || 'completed' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| PHP Security Linter | ${{ steps.security-linter.outcome || 'completed' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Drush Advisories | ${{ steps.drush-security.outcome || 'completed' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Composer Audit | ${{ steps.composer-audit.outcome || 'completed' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Semgrep SAST | ${{ steps.semgrep.outcome || 'completed' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Trivy Scanner | ${{ steps.trivy.outcome || 'completed' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Gitleaks Secrets | ${{ steps.gitleaks.outcome || 'completed' }} |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Testing" >> $GITHUB_STEP_SUMMARY
          echo "| Check | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Tests | ${{ steps.tests.outcome || 'completed' }} |" >> $GITHUB_STEP_SUMMARY
