#!/usr/bin/env bash
# deferred-findings-spec.sh — the deferred-findings block inside build-critique-assert.sh
# (the section commented "deferred findings (v5.35.0+)") is enforced, and the enforcement
# can fail.
#
# THE DEFECT THIS DEFENDS AGAINST. PREMATURE FIXES. A critic correctly reported that a method
# had no production caller — true, and unfixable, because the caller was a component three
# steps later in the build order. With nowhere to put a finding it could not answer yet, the
# builder answered it anyway, by writing a spec for the absent caller. That answer produced
# the next round's critical, whose answer produced the round after it. Three of the four
# unfixable findings on that build were self-generated by trying to close the first one.
#
# Whether a finding was premature is not machine-checkable. Whether the builder SAID so is.
# A finding that cannot be resolved yet names what it is waiting on and why answering now
# would be wrong, and then stops blocking. A deferral short any of those three is a finding
# nobody will return to, and it reads on disk exactly like one that was handled.
#
# These assertions were previously section 7e of `critique-round-budget-spec.sh`, a file named
# for the round budget, which no longer exists. They are rehomed to a spec named for the thing
# they test rather than deleted with the block they were sitting inside.
#
# Every assertion runs against a real fixture task folder written through gate-audit-write.sh,
# never read off prose. Message-content checks are included deliberately: several branches
# share the same verdict/unresolved/exit-code triple as their neighbour, so a mutation that
# disables one branch but falls through to another would otherwise pass unnoticed.

set -eu
PLUGIN_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
G="${PLUGIN_ROOT}/scripts/build-critique-assert.sh"
W="${PLUGIN_ROOT}/scripts/gate-audit-write.sh"

FAIL=0
# Every assertion goes through one of these two, so the counter below counts assertions that
# actually ran. `N=$((N+1))` and not `((N++))`: under `set -e` the arithmetic form returns 1
# when the result is 0 and aborts the whole file on the first assertion.
ASSERTIONS=0
fail_check() { ASSERTIONS=$((ASSERTIONS+1)); printf 'FAIL: %s\n' "$1" >&2; FAIL=1; }
pass_check() { ASSERTIONS=$((ASSERTIONS+1)); printf 'OK   %s\n' "$1"; }

for f in "$G" "$W"; do
  [ -f "$f" ] || { printf 'FAIL: %s missing\n' "$f" >&2; exit 1; }
done
command -v jq >/dev/null 2>&1 || { printf 'FAIL: jq required\n' >&2; exit 1; }

T=$(mktemp -d); trap 'rm -rf "$T"' EXIT

# An otherwise-valid, otherwise-passing build-critique payload: tdd, contract and the accept
# verdict are all already clean, so every fixture below isolates the block it is named for.
# The component row carries no `accept` key and `rounds: 1`, which the accept block reads as a
# component that was never repaired and therefore owes no verdict.
GOOD='{"build_identity":{"head":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","files_digest":"da885006a736ed9ce06e3736845717d7f70d58abf15995f8977f551bbfafbf1f","files":["src/A.php"]},"verdict":"pass","components_declared":1,"components_critiqued":1,"uncritiqued":[],
 "closing_fixes":{"applied":0},
 "tdd":{"red_observed":1,"passed_first_run":0,"unobserved":[]},
 "contract":{"baseline":"captured","changed":[]},
 "integration":{"ran":false,"reason":"single-component fixture"},
 "components":[{"component":"a","runtime":"executed","blocking":false}]}'

mktask() { d="$T/$1"; mkdir -p "$d" >/dev/null 2>&1; printf '%s' "$d"; }

# write_record <folder> <jq filter over GOOD>
write_record() {
  bash "$W" "$1" build-critique "$(printf '%s' "$GOOD" | jq -c "$2")" >/dev/null 2>&1
}

# run <folder> [flags...] -> sets OUT (json) and RC
# The build-critique gate compares the record's build_identity against the change set the caller
# resolved. This spec is about a different block, so it hands the gate a change set that agrees
# with GOOD's identity and keeps the subject of each case the thing it is named for.
CSF="$(mktemp)"
printf '%s' '{"schema_version":"1.0","base":"main","merge_base":"abc","head":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","files":["src/A.php"],"untracked":[],"empty_reason":null,"warnings":[]}' > "$CSF"

run() {
  d="$1"; shift
  set +e
  OUT=$(bash "$G" "$d" --change-set-file "$CSF" "$@" 2>/dev/null); RC=$?
  set -e
}

verdict_is() { # verdict_is <expected> <label>
  V=$(printf '%s' "$OUT" | jq -r '.verdict')
  if [ "$V" = "$1" ]; then pass_check "$2"; else fail_check "$2 (got verdict=$V, rc=$RC)"; fi
}

unresolved_is() { # unresolved_is <true|false> <label>
  U=$(printf '%s' "$OUT" | jq -r '.unresolved')
  if [ "$U" = "$1" ]; then pass_check "$2"; else fail_check "$2 (got unresolved=$U)"; fi
}

rc_is() { # rc_is <expected> <label>
  if [ "$RC" = "$1" ]; then pass_check "$2"; else fail_check "$2 (got rc=$RC)"; fi
}

msg_has() { # msg_has <substring> <label>
  if printf '%s' "$OUT" | jq -r '.messages|join(" | ")' | grep -qF "$1"; then
    pass_check "$2"
  else
    fail_check "$2 (messages: $(printf '%s' "$OUT" | jq -c '.messages'))"
  fi
}

msg_lacks() { # msg_lacks <substring> <label>
  if printf '%s' "$OUT" | jq -r '.messages|join(" | ")' | grep -qF "$1"; then
    fail_check "$2 (messages: $(printf '%s' "$OUT" | jq -c '.messages'))"
  else
    pass_check "$2"
  fi
}

# ------------------------------------- 1. a deferral must name what it waits for
# "This method has no production caller" is true and unfixable when the caller is three
# components away. With nowhere to put it, a live build wrote a spec for the absent caller,
# and that answer produced the next round's critical.

D=$(mktask deferral_no_blocker)
write_record "$D" '.components=[{"component":"a","runtime":"executed","blocking":false,"rounds":1}]
  | .rounds=[{"round":1,"deferred":[{"finding":"verify() has no production caller"}]}]'
run "$D"
verdict_is fail "a deferral naming no blocked_on fails"
unresolved_is true "an unanchored deferral is a could-not-tell"
msg_has "the component they wait on" "the message says why the deferral is not acceptable"

D=$(mktask deferral_good)
write_record "$D" '.components=[{"component":"a","runtime":"executed","blocking":false,"rounds":1}]
  | .rounds=[{"round":1,"deferred":[{"finding":"verify() has no production caller",
      "blocked_on":"drush-commands","why_now_is_wrong":"the caller is step 6 of the build order"}]}]'
run "$D"
verdict_is pass "a deferral that names its blocker passes and does not block"
rc_is 0 "a well-formed deferral exits 0"
msg_has "deferred to a component not yet built" "deferred findings are surfaced, not silently dropped"

D=$(mktask deferral_empty_finding)
write_record "$D" '.components=[{"component":"a","runtime":"executed","blocking":false,"rounds":1}]
  | .rounds=[{"round":1,"deferred":[{"finding":"","blocked_on":"drush-commands"}]}]'
run "$D"
verdict_is fail "a deferral with no finding text fails too"

# --------------- 2. ordering: a missing tdd block is checked BEFORE deferred findings,
# so a payload that violates both never reaches the deferred-findings code at all.
#
# The ordering property is real and nothing else covers it. It used to be asserted against the
# round budget, which sat between these two blocks and no longer exists; it is re-anchored to
# the surviving neighbours on either side of where that block was.

D=$(mktask order_tdd_before_deferred)
write_record "$D" 'del(.tdd)
  | .components=[{"component":"a","runtime":"executed","blocking":false,"rounds":1}]
  | .rounds=[{"round":1,"deferred":[{"finding":"verify() has no production caller"}]}]'
run "$D"
verdict_is fail "a payload missing tdd AND carrying a malformed deferral still fails"
unresolved_is true "the double violation is unresolved"
rc_is 1 "the double violation exits 1"
msg_has "the record carries no tdd block" \
  "the missing-tdd message fires: tdd is checked before the deferred findings"
msg_lacks "the component they wait on" \
  "the deferral message never appears -- the script already exited on the missing tdd block"
msg_lacks "omits red_observed, passed_first_run or unobserved" \
  "no later tdd sub-check message appears either -- the script exits on the very first tdd check"
N_MSGS=$(printf '%s' "$OUT" | jq -r '.messages|length')
if [ "$N_MSGS" = "1" ]; then
  pass_check "exactly one message is emitted -- the script exits immediately, it does not fall through"
else
  fail_check "exactly one message is emitted -- the script exits immediately, it does not fall through (got $N_MSGS: $(printf '%s' "$OUT" | jq -c '.messages'))"
fi

# ------------- 3. ordering: deferred findings are checked BEFORE the contract block,
# so a payload that violates both reports the malformed deferral, not the missing contract.

D=$(mktask order_deferred_before_contract)
write_record "$D" 'del(.contract)
  | .components=[{"component":"a","runtime":"executed","blocking":false,"rounds":1}]
  | .rounds=[{"round":1,"deferred":[{"finding":"verify() has no production caller"}]}]'
run "$D"
verdict_is fail "a payload with a malformed deferral AND no contract block still fails"
unresolved_is true "the double violation is unresolved"
rc_is 1 "the double violation exits 1"
msg_has "the component they wait on" \
  "the deferral message fires: deferred findings are checked before the contract block"
msg_lacks "the record carries no contract block" \
  "the missing-contract message never appears -- the script already exited on the deferral"

# ----------------------------------------------------- the asserted assertion count
#
# A spec that skips a whole block still prints "all checks passed": nothing in the loop above
# notices a fixture that never ran, and a `set -e` abort inside a helper would end the file
# quietly with FAIL still 0. The count is the assertion that every other assertion happened.
# Update it deliberately, in the same commit as the case you added or removed.
EXPECTED_ASSERTIONS=19
if [ "$ASSERTIONS" != "$EXPECTED_ASSERTIONS" ]; then
  printf 'FAIL: expected %s assertions, ran %s -- a block was skipped, added or removed\n' \
    "$EXPECTED_ASSERTIONS" "$ASSERTIONS" >&2
  FAIL=1
fi

if [ "$FAIL" = "0" ]; then
  printf '\ndeferred-findings-spec: all checks passed (%s assertions)\n' "$ASSERTIONS"
else
  printf '\ndeferred-findings-spec: FAILURES (%s assertions ran)\n' "$ASSERTIONS" >&2
fi
exit "$FAIL"
